service: apibsale-service

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  BsaleFunc:
    handler: index.handler
    events:
      - http:
          path: product
          method: get
          cors: true
      - http:
          path: product/{id}
          method: get
          cors: true
      - http:
          path: category/{id}
          method: get
          cors: true
      - http:
          path: category
          method: get
          cors: true

plugins:
  - serverless-offline